import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body>
        <header className="container flex justify-between mb-8">
          
          <nav className="flex gap-5">
            <Link href="/">
              Home
            </Link><br/>
            <Link href="/newswire">
              noticias
            </Link>
          </nav>
        </header>
        <main className={inter.className}>{children}</main>
      </body>

    </html>
  );
}
